version: '3'
services:

  ld-r:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SE
      - SE_API_KEY
      - SE_HOST
      - SE_PORT=8182
      - SE_PATH=/sparql
      - SE_PROTOCOL=https
    volumes:
      - ./logs:/ld-r/logs
    ports:
      - 8080:4000



